/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	scheme "github.com/costinm/uk8s/client/echo/versioned/scheme"
	v1 "github.com/costinm/uk8s/echo/apis/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EchosGetter has a method to return a EchoInterface.
// A group's client should implement this interface.
type EchosGetter interface {
	Echos(namespace string) EchoInterface
}

// EchoInterface has methods to work with Echo resources.
type EchoInterface interface {
	Create(ctx context.Context, echo *v1.Echo, opts metav1.CreateOptions) (*v1.Echo, error)
	Update(ctx context.Context, echo *v1.Echo, opts metav1.UpdateOptions) (*v1.Echo, error)
	UpdateStatus(ctx context.Context, echo *v1.Echo, opts metav1.UpdateOptions) (*v1.Echo, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Echo, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.EchoList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Echo, err error)
	EchoExpansion
}

// echos implements EchoInterface
type echos struct {
	client rest.Interface
	ns     string
}

// newEchos returns a Echos
func newEchos(c *Uk8sV1Client, namespace string) *echos {
	return &echos{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the echo, and returns the corresponding echo object, and an error if there is any.
func (c *echos) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Echo, err error) {
	result = &v1.Echo{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("echos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Echos that match those selectors.
func (c *echos) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EchoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EchoList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("echos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested echos.
func (c *echos) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("echos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a echo and creates it.  Returns the server's representation of the echo, and an error, if there is any.
func (c *echos) Create(ctx context.Context, echo *v1.Echo, opts metav1.CreateOptions) (result *v1.Echo, err error) {
	result = &v1.Echo{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("echos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(echo).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a echo and updates it. Returns the server's representation of the echo, and an error, if there is any.
func (c *echos) Update(ctx context.Context, echo *v1.Echo, opts metav1.UpdateOptions) (result *v1.Echo, err error) {
	result = &v1.Echo{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("echos").
		Name(echo.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(echo).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *echos) UpdateStatus(ctx context.Context, echo *v1.Echo, opts metav1.UpdateOptions) (result *v1.Echo, err error) {
	result = &v1.Echo{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("echos").
		Name(echo.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(echo).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the echo and deletes it. Returns an error if one occurs.
func (c *echos) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("echos").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *echos) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("echos").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched echo.
func (c *echos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Echo, err error) {
	result = &v1.Echo{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("echos").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
