/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	internalinterfaces "github.com/costinm/uk8s/cachedclient/echo/informer/externalversions/internalinterfaces"
	v1 "github.com/costinm/uk8s/cachedclient/echo/lister/apis/v1"
	echo "github.com/costinm/uk8s/client/echo"
	apisv1 "github.com/costinm/uk8s/echo/apis/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EchoInformer provides access to a shared informer and lister for
// Echos.
type EchoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.EchoLister
}

type echoInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEchoInformer constructs a new informer for Echo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEchoInformer(client echo.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEchoInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEchoInformer constructs a new informer for Echo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEchoInformer(client echo.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Uk8sV1().Echos(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Uk8sV1().Echos(namespace).Watch(context.TODO(), options)
			},
		},
		&apisv1.Echo{},
		resyncPeriod,
		indexers,
	)
}

func (f *echoInformer) defaultInformer(client echo.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEchoInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *echoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisv1.Echo{}, f.defaultInformer)
}

func (f *echoInformer) Lister() v1.EchoLister {
	return v1.NewEchoLister(f.Informer().GetIndexer())
}
